### PR TITLE
Replaced whitelist_externals with allowlist_externals in tox and removed tox-battery

### PR DESCRIPTION
**Pull request by zubairshakoorarbisoft**
Issue: https://github.com/edx/edx-arch-experiments/issues/130

### CODE REVIEW

**Review by UsamaSadiq — APPROVED** [review]
Tests already failing on master branch. Will try to fix the test failures in a separate follow up PR.

**Comment by UsamaSadiq** [comment]
@feanil would it be okay if we merge this PR with the test failures since the failures are not related to the changes made in the PR.

**Comment by feanil** [comment]
@UsamaSadiq https://github.com/openedx/xblock-google-drive/pull/68 resolves the issue on master, let's merge that first and then you can merge this one after a rebase.

**Comment by UsamaSadiq** [comment]
@zubairshakoorarbisoft could you try rebasing the PR. The errors should be resolved now.

**Pull request merged**
